[phases.setup]
nixPkgs = ["nodejs_18", "rustc", "cargo", "wasm-pack", "pkg-config"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "cargo generate-lockfile",
  "npm run build"
]

[start]
cmd = "npm start" 